import google.generativeai as genai

#retrieve API key from Gemini API
api_key = "AIzaSyAiArDY6jVsPpoc8DVohAmK15oTplQHwWo"

# Configure the API key
genai.configure(api_key=api_key)

def generate_inspirational_quote():
    """
    Generates a short inspirational quote using Gemini API.

    Returns:
        str: An inspirational quote generated by Gemini API.
    """
    prompt = "Generate a short and inspirational quote to start your morning! Add a dog pun to it."
    model = genai.GenerativeModel("gemini-1.5-flash")
    response = model.generate_content(prompt)
    return response.text.strip()

if __name__ == "__main__":
    quote = generate_inspirational_quote()
    print(f"Inspirational Quote: {quote}")
